# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "975730513b61174505a0fe69a28cc733"
name = "app-extension-1"
handle = "app-extension-29"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "nick-drishinski-theme.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
